name: First workflow
on: [push]

jobs: 
    run-shell-commands: 
        runs-on: ubuntu-latest
        steps:
         - name: echo a string
           run: echo "Hello world"
         - name: Multiple command
           run: | 
            node -v
            npm -v
    parallel-job-macos:
        runs-on: macos-latest
        steps: 
            - name: view SW version
              run: sw_vers
    dependent-job:
     runs-on: window latest
     needs: run-shell-commands
     steps: 
      - name: echo a string
        run: write-Output "Window Stirng"
      - name: Error
        run: doesnotexist
